version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - "POSTGRES_DB=fiap_blog"
      - "POSTGRES_USER=fiap_blog"
      - "POSTGRES_PASSWORD=root"
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: