version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@2024
      POSTGRES_DB: learnon_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./path/to/your/app  # Substitua pelo caminho para o seu Dockerfile da aplicação Node.js
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:root%402024@postgres:5432/learnon_dev  # URL de conexão com o banco de dados

volumes:
  postgres-data:
    driver: local
