version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_fiap

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - rede_fiap

volumes:
  postgres_data:

networks:
  rede_fiap:
